version: 1.0.1.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: >-
    cd Src

    nuget restore

    cd ..
build:
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal