// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Codge.BasicModel.Templates.CS.Templates.Types
{
    using System.IO;
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Codge.DataModel;
    using Codge.Generator;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Work\Projects\codge_\Src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\Types\Composite.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class Composite : T4TemplateAction<TypeBase>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\nnamespace Types.");
            
            #line 10 "C:\Work\Projects\codge_\Src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\Types\Composite.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type.Namespace.GetFullName(".")));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\tpublic class ");
            
            #line 12 "C:\Work\Projects\codge_\Src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\Types\Composite.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n\t    public ");
            
            #line 14 "C:\Work\Projects\codge_\Src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\Types\Composite.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type.Name));
            
            #line default
            #line hidden
            this.Write("()\r\n\t\t{}\r\n\r\n");
            
            #line 17 "C:\Work\Projects\codge_\Src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\Types\Composite.tt"
				
					if(Type.Fields.Any())
					{

            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic ");
            
            #line 22 "C:\Work\Projects\codge_\Src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\Types\Composite.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 22 "C:\Work\Projects\codge_\Src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\Types\Composite.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelBehaviour.GetCtorParamters(Type)));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n");
            
            #line 24 "C:\Work\Projects\codge_\Src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\Types\Composite.tt"
				
						foreach(var field in Type.Fields)
						{

            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 28 "C:\Work\Projects\codge_\Src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\Types\Composite.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelBehaviour.GetMemberName(field)));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 28 "C:\Work\Projects\codge_\Src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\Types\Composite.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelBehaviour.GetParameterName(field)));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 29 "C:\Work\Projects\codge_\Src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\Types\Composite.tt"
				
						}

            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\r\n\r\n");
            
            #line 35 "C:\Work\Projects\codge_\Src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\Types\Composite.tt"
				
					}

					foreach(var field in Type.Fields)
					{

            
            #line default
            #line hidden
            this.Write("\t\tpublic\t");
            
            #line 41 "C:\Work\Projects\codge_\Src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\Types\Composite.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelBehaviour.GetNativeType(field)));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 41 "C:\Work\Projects\codge_\Src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\Types\Composite.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelBehaviour.GetMemberName(field)));
            
            #line default
            #line hidden
            this.Write(" {get; set;}\r\n");
            
            #line 42 "C:\Work\Projects\codge_\Src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\Types\Composite.tt"
				
					}

            
            #line default
            #line hidden
            this.Write("\t}\r\n}\r\n\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 49 "C:\Work\Projects\codge_\Src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\Types\Composite.tt"

	

	public CompositeType Type {get; private set;}

	public Composite(TypeBase type, IModelBehaviour modelBehaviour)
        : base(modelBehaviour)
	{
		Type = type as CompositeType;
	}

	public override bool IsApplicable()
	{
		return Type!=null;
	}

	public override PathAndContent Execute(Context context)
	{
		return new PathAndContent(new ItemInformation(Type.QName(), "Types.cs"), TransformText());
	}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
