// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Codge.BasicModel.Templates.CS.Templates.Types
{
    using System.IO;
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Codge.DataModel;
    using Codge.Generator.Common;
    using Codge.BasicModel.Templates.CS;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Work\Projects\codge_\Src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\Types\Enum.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class Enum : T4TemplateAction<TypeBase>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\nusing System.Collections.Generic;\r\n\r\nnamespace Types.");
            
            #line 13 "C:\Work\Projects\codge_\Src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\Types\Enum.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type.Namespace.GetFullName(".")));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\tpublic enum ");
            
            #line 15 "C:\Work\Projects\codge_\Src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\Types\Enum.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n\r\n");
            
            #line 18 "C:\Work\Projects\codge_\Src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\Types\Enum.tt"
				
                    string prefix = string.Empty;
					foreach(var item in Type.Items)
					{

            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 23 "C:\Work\Projects\codge_\Src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\Types\Enum.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(prefix));
            
            #line default
            #line hidden
            
            #line 23 "C:\Work\Projects\codge_\Src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\Types\Enum.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelBehaviour.GetEnumItemName(Type, item)));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 23 "C:\Work\Projects\codge_\Src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\Types\Enum.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Value));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 24 "C:\Work\Projects\codge_\Src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\Types\Enum.tt"
							
						prefix = ",";
					}

            
            #line default
            #line hidden
            this.Write("\t\r\n\t}\r\n\r\n    public static class ");
            
            #line 31 "C:\Work\Projects\codge_\Src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\Types\Enum.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type.Name));
            
            #line default
            #line hidden
            this.Write("Converter\r\n\t{\r\n        private static string[] _values = new string[");
            
            #line 33 "C:\Work\Projects\codge_\Src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\Types\Enum.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type.Items.Count()));
            
            #line default
            #line hidden
            this.Write("];\r\n        private static IDictionary<string, ");
            
            #line 34 "C:\Work\Projects\codge_\Src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\Types\Enum.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type.Name));
            
            #line default
            #line hidden
            this.Write(" > _stringToEnum = new Dictionary<string, ");
            
            #line 34 "C:\Work\Projects\codge_\Src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\Types\Enum.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type.Name));
            
            #line default
            #line hidden
            this.Write(" >();\r\n\r\n        static ");
            
            #line 36 "C:\Work\Projects\codge_\Src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\Types\Enum.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type.Name));
            
            #line default
            #line hidden
            this.Write("Converter()\r\n        {\r\n");
            
            #line 38 "C:\Work\Projects\codge_\Src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\Types\Enum.tt"
				
					foreach(var item in Type.Items)
					{

            
            #line default
            #line hidden
            this.Write("\t\t    _values[(int)");
            
            #line 42 "C:\Work\Projects\codge_\Src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\Types\Enum.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type.Name));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 42 "C:\Work\Projects\codge_\Src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\Types\Enum.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelBehaviour.GetEnumItemName(Type, item)));
            
            #line default
            #line hidden
            this.Write("] = \"");
            
            #line 42 "C:\Work\Projects\codge_\Src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\Types\Enum.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\";\r\n            _stringToEnum.Add(\"");
            
            #line 43 "C:\Work\Projects\codge_\Src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\Types\Enum.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 43 "C:\Work\Projects\codge_\Src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\Types\Enum.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type.Name));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 43 "C:\Work\Projects\codge_\Src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\Types\Enum.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ModelBehaviour.GetEnumItemName(Type, item)));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 44 "C:\Work\Projects\codge_\Src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\Types\Enum.tt"
						
					}

            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n        public static string ConvertToString(");
            
            #line 49 "C:\Work\Projects\codge_\Src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\Types\Enum.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type.Name));
            
            #line default
            #line hidden
            this.Write(" value)\r\n        {\r\n            return _values[(int)value];\r\n\t    }\r\n\r\n        pu" +
                    "blic static ");
            
            #line 54 "C:\Work\Projects\codge_\Src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\Types\Enum.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type.Name));
            
            #line default
            #line hidden
            this.Write(" ConvertToEnum(string value)\r\n        {\r\n            return _stringToEnum[value];" +
                    "\r\n\t    }\r\n\r\n\t\tpublic static ");
            
            #line 59 "C:\Work\Projects\codge_\Src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\Types\Enum.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type.Name));
            
            #line default
            #line hidden
            this.Write("? TryConvertToEnum(string value)\r\n        {\r\n            ");
            
            #line 61 "C:\Work\Projects\codge_\Src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\Types\Enum.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Type.Name));
            
            #line default
            #line hidden
            this.Write(" enumValue;\r\n            if(!_stringToEnum.TryGetValue(value, out enumValue))\r\n  " +
                    "          {\r\n                return null;\r\n            }\r\n            return enu" +
                    "mValue;\r\n\t    }\r\n\t}\r\n}\r\n\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 72 "C:\Work\Projects\codge_\Src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\Types\Enum.tt"

	public EnumerationType Type{get; private set;}

	public Enum(TypeBase type, ModelBehaviour modelBehaviour)
        : base(modelBehaviour)
	{
		Type = type as EnumerationType;
	}

	public override bool IsApplicable()
	{
		return Type!=null;
	}

	public override PathAndContent Execute(Context context)
	{
		return new PathAndContent(new ItemInformation(Type.QName(), "Types.cs"), TransformText());
	}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
