// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Codge.BasicModel.Templates.CS.Templates
{
    using System.IO;
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using Codge.DataModel;
    using Codge.Generator.Common;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Work\Codge\src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\PofConfig.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class PofConfig : T4TemplateAction<Model>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("<?xml version=\"1.0\"?>\r\n<pof-config xmlns=\"http://schemas.tangosol.com/pof\">\r\n  <u" +
                    "ser-type-list>\r\n");
            
            #line 12 "C:\Work\Codge\src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\PofConfig.tt"
				
					foreach(var type in Model.Namespace.AllTypes().Where(t => t is CompositeType))
					{

            
            #line default
            #line hidden
            this.Write("    <user-type>\r\n      <type-id>");
            
            #line 17 "C:\Work\Codge\src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\PofConfig.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type.Id));
            
            #line default
            #line hidden
            this.Write("</type-id>\r\n      <class-name>");
            
            #line 18 "C:\Work\Codge\src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\PofConfig.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type.QName()));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 18 "C:\Work\Codge\src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\PofConfig.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type.AssemblyName()));
            
            #line default
            #line hidden
            this.Write("</class-name>\r\n      <serializer>\r\n        <class-name>");
            
            #line 20 "C:\Work\Codge\src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\PofConfig.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type.SerialiserQName()));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 20 "C:\Work\Codge\src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\PofConfig.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(type.AssemblyName()));
            
            #line default
            #line hidden
            this.Write("</class-name>\r\n      </serializer>\r\n    </user-type>\r\n");
            
            #line 23 "C:\Work\Codge\src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\PofConfig.tt"
						
					}

            
            #line default
            #line hidden
            this.Write("  </user-type-list>\r\n</pof-config>\r\n\r\n\r\n\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 32 "C:\Work\Codge\src\Models\Basic\CS\Codge.BasicModel.Templates\Templates\PofConfig.tt"

	public Model Model{get; private set;}

	public PofConfig(Model model, ModelBehaviour modelBehaviour)
        : base(modelBehaviour)
	{
		Model = model;
	}

	public override bool IsApplicable()
	{
		return true;
	}

	public override PathAndContent Execute(Context context)
	{
		return new PathAndContent(new ItemInformation("pof",".config"), TransformText());
	}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
